inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"

##################### Style ##################################

Style/AndOr:
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  AutoCorrect: false
  Exclude:
    - "spec/**/*"

Style/CollectionMethods:
  PreferredMethods:
    detect: "detect"
    find: "detect"
    inject: "inject"
    reduce: "inject"

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/EmptyElse:
  EnforcedStyle: empty

Layout/ExtraSpacing:
  Exclude:
    - "db/migrate/*.rb"

Style/FormatString:
  EnforcedStyle: percent

Style/GuardClause:
  MinBodyLength: 5

Style/HashSyntax:
  Exclude:
    - "**/*.rake"
    - "Rakefile"

Style/IfUnlessModifier:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/Lambda:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Style/PerlBackrefs:
  AutoCorrect: false

Naming/PredicateName:
  ForbiddenPrefixes:
    - "is_"
    - "have_"
  NamePrefix:
    - "is_"
    - "have_"

Style/RedundantSelf:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/Semicolon:
  Exclude:
    - "spec/**/*"

Style/SignalException:
  EnforcedStyle: only_raise

Layout/SpaceAroundOperators:
  AllowForAlignment: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

##################### Lint ##################################

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

##################### Metrics ##################################

Layout/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

Metrics/PerceivedComplexity:
  Max: 8

##################### New Cops ##################################

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

# ... (他の新しいcopsも同様に追加)

Style/YAMLFileRead:
  Enabled: true

NewCops: enable
